/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pair-scan`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/h/[serverId]`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/new`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/open-project`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/sessions`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/settings`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/agent/[agentId]`, params: Router.UnknownInputParams & { serverId: string | number;agentId: string | number; } } | { pathname: `/h/[serverId]/workspace/[workspaceId]`, params: Router.UnknownInputParams & { serverId: string | number;workspaceId: string | number; } } | { pathname: `/settings/[section]`, params: Router.UnknownInputParams & { section: string | number; } } | { pathname: `/settings/hosts/[serverId]`, params: Router.UnknownInputParams & { serverId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pair-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/h/[serverId]`, params: Router.UnknownOutputParams & { serverId: string; } } | { pathname: `/h/[serverId]/new`, params: Router.UnknownOutputParams & { serverId: string; } } | { pathname: `/h/[serverId]/open-project`, params: Router.UnknownOutputParams & { serverId: string; } } | { pathname: `/h/[serverId]/sessions`, params: Router.UnknownOutputParams & { serverId: string; } } | { pathname: `/h/[serverId]/settings`, params: Router.UnknownOutputParams & { serverId: string; } } | { pathname: `/h/[serverId]/agent/[agentId]`, params: Router.UnknownOutputParams & { serverId: string;agentId: string; } } | { pathname: `/h/[serverId]/workspace/[workspaceId]`, params: Router.UnknownOutputParams & { serverId: string;workspaceId: string; } } | { pathname: `/settings/[section]`, params: Router.UnknownOutputParams & { section: string; } } | { pathname: `/settings/hosts/[serverId]`, params: Router.UnknownOutputParams & { serverId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/pair-scan${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pair-scan`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | `/h/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/new${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/open-project${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/sessions${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/settings${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/agent/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/h/${Router.SingleRoutePart<T>}/workspace/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/settings/hosts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/h/[serverId]`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/new`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/open-project`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/sessions`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/settings`, params: Router.UnknownInputParams & { serverId: string | number; } } | { pathname: `/h/[serverId]/agent/[agentId]`, params: Router.UnknownInputParams & { serverId: string | number;agentId: string | number; } } | { pathname: `/h/[serverId]/workspace/[workspaceId]`, params: Router.UnknownInputParams & { serverId: string | number;workspaceId: string | number; } } | { pathname: `/settings/[section]`, params: Router.UnknownInputParams & { section: string | number; } } | { pathname: `/settings/hosts/[serverId]`, params: Router.UnknownInputParams & { serverId: string | number; } };
    }
  }
}
